// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnLBxvDm_LH1dYDZAaqoPs5R4q6iFcjlc',
    appId: '1:872135031945:web:40402bd368daf0af2dda58',
    messagingSenderId: '872135031945',
    projectId: 'hello-radiko',
    authDomain: 'hello-radiko.firebaseapp.com',
    storageBucket: 'hello-radiko.firebasestorage.app',
    measurementId: 'G-4JV8NZXGWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpDYUlCF9400fyVVwZDoW1fll1pUc4478',
    appId: '1:872135031945:android:f3617a9b601247762dda58',
    messagingSenderId: '872135031945',
    projectId: 'hello-radiko',
    storageBucket: 'hello-radiko.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKFI_zCgW7p3hO-GA7ugLHBw4-2GL3AR8',
    appId: '1:872135031945:ios:b9cb21d15844df7f2dda58',
    messagingSenderId: '872135031945',
    projectId: 'hello-radiko',
    storageBucket: 'hello-radiko.firebasestorage.app',
    iosBundleId: 'com.hello.radiko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnLBxvDm_LH1dYDZAaqoPs5R4q6iFcjlc',
    appId: '1:872135031945:web:58b04330f933ebd72dda58',
    messagingSenderId: '872135031945',
    projectId: 'hello-radiko',
    authDomain: 'hello-radiko.firebaseapp.com',
    storageBucket: 'hello-radiko.firebasestorage.app',
    measurementId: 'G-VKG6DCPRMM',
  );

}